PACKAGE_NAME="ec_su_axb35"
PACKAGE_VERSION="1.0"

BUILT_MODULE_NAME[0]="ec_su_axb35"
DEST_MODULE_LOCATION[0]="/updates"

MAKE[0]="make KERNEL_BUILD=/lib/modules/${kernelver}/build"
CLEAN="make KERNEL_BUILD=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
